# Generated by Django 4.1.4 on 2022-12-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Familiares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='edad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familiar',
            name='esta_vivo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
